[server]
enableCORS = true
port = 8501

[theme]
primaryColor = "#4158D0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showErrorDetails = false

[server]
hideDefaultAppearance = true